### ISSUE TITLE
Update to latest version of Prisma

### ISSUE THREAD

**Issue by jensmeindertsma** [CarterGrimmeisen/zod-prisma#1]
Hey Carter,
I came across this project and I'd love to use it. Really awesome to see that someone else already put the hard work into the project that I need. But I really need to use Prisma@3, and this project's dependencies require Prisma@2. Is there any possibility that I could help you update this project to Prisma@3?

**Comment by CarterGrimmeisen** [comment]
Hey there! Thanks for your interest in the package. I've updated the dependencies to enable use with Prisma@3, and published a new version to npm. Let me know if you run into any issues!

**Comment by jensmeindertsma** [comment]
Awesome. Thanks for doing this so quickly, even in the weekend! Enjoy your weekend!

**Comment by CarterGrimmeisen** [comment]
No problem! You enjoy yours as well!
