### ISSUE TITLE
Create schema for create 

### ISSUE THREAD

**Issue by kenneho** [CarterGrimmeisen/zod-prisma#20]
Hi.

Thanks for this great utility. 

I ran it on my schema, and got a file `company.ts` containing something like this: 
```
export const _BlogPostModel = z.object({
  id: z.number().int(),
  createdAt: z.date(),
  updatedAt: z.date(),
  name: z.string(),
})

export interface CompleteBlogPost extends BlogPost {
  comments: CompleteComment[]
}

export const BlogPostModel: z.ZodSchema<CompleteBlogPost> = z.lazy(() =>
  _BlogPostModel.extend({
    comments: CommentModel.array(),
  })
)
```
I'm not able to use BlogPostModel to validate input for updates to blogposts. But when creating a new blog post however, I need to omit id, createdAt and updatedAt. If I make use of `_BlogPostModel`, I could do something like this: 

```
# Location: Some file in my app, where I handle database access 
import { _BlogPostModel } from "db/zod/blogpost"
export const CreateBlogPostModel = _BlogPostModel.omit({
  id: true,
  createdAt: true,
  updatedAt: true,
})
```
The latter example is very hacky, as the underscore-prefixed variable I assume is not supposed to be used like this. On the other hand, `BlogPostModel` doesn't support the `omit` operation. 

What's the recommended way to generate zod schemas that omit only the three fields mentioned? 
A feature request could be to have zod-prisma to export one schema containing everything (like it does today) called for example `BlogPostUpdateModel`, plus a `BlogPostCreateModel` which omits the mentioned fields.

**Comment by CarterGrimmeisen** [comment]
Yep, unfortunately not being able to omit is a limitation of the z.lazy models that I haven't figured out how to overcome yet.

However, in the config for my generator you can specify relationModel = true instead of default and that will change the naming to something that makes more sense for your use case.

**Comment by kenneho** [comment]
Thanks, I'll try that.
