### ISSUE TITLE
Generated unknown type results in ReferenceError

### ISSUE THREAD

**Issue by michalochman** [CarterGrimmeisen/zod-prisma#34]
Hi! Thanks for this amazing time saver.

I have started using it and I noticed that the `unknown` type is incorrectly generated due to a typo.
The issue results in the following runtime error: `ReferenceError: unknown is not defined`.

You can find the typo here:
https://github.com/CarterGrimmeisen/zod-prisma/blob/1962bec2ef3fe13bd411be7575827f7e7cdcbbaa/src/types.ts#L8

The line should most likely read:
```diff
- let zodType = 'unknown()' 
+ let zodType = 'z.unknown()' 
```

**Comment by CarterGrimmeisen** [comment]
Okay, new version has been published to NPM and I'm glad this project could save you some time! 👍
