### ISSUE TITLE
Output formatting options

### ISSUE THREAD

**Issue by franky47** [CarterGrimmeisen/zod-prisma#43]
As I tend to reserve PascalCase for class definitions, and camelCase for objects and literal definitions, it would be nice to be able to configure the output names of the generated Zod schemas:

```ts
export const userModel = z.object(...)
```

Also, as Zod names its objects _schemas_, allowing to change the suffix would be nice too:

```ts
export const userSchema = z.object(...)
```

Suggested API (with current defaults):

```graphql
generator zod {
  provider      = "zod-prisma"
  output        = "./zod"
  modelCase     = "PascalCase" // options: "camelCase" | "PascalCase"
  modelSuffix   = "Model"
}
```

I can open a PR if you're interested.

Related packages: https://github.com/blakeembrey/change-case

**Comment by CarterGrimmeisen** [comment]
Published with version 0.3.0! Thank you so much for your contribution!
