### ISSUE TITLE
Allow specifying representation of Decimal type

### ISSUE THREAD

**Issue by michalochman** [CarterGrimmeisen/zod-prisma#62]
Hi, currently Decimal is represented with `zod.number()`. While this may be some workable default, I would like to be able to use [decimal.js](https://github.com/MikeMcl/decimal.js), which is also [used by Prisma](https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields#working-with-decimal).

`Decimal` constructor takes `number | string | Decimal` as input and returns `Decimal` object.

Now imagine that you fetch data using HTTP, then you will most likely end up with some JSON object you want to parse.
Since JSON does not support Decimal objects, the input to `Decimal` could be narrowed to just `number | string`, which is ok, as your decimal data could be encoded by a string or a number – I would argue that the former is better as you don't lose precision when transferring data from your API to your consumers.

Given the above, this is how we could represent a Decimal type:

```ts
import { z } from "zod";
import { Decimal } from "decimal.js";

const decimalParser = z
  .union([z.string(), z.number()])
  .transform(value => new Decimal(value));

decimalParser.parse(42); // ok, returns Decimal instance
decimalParser.parse("3.14159265359"); // ok, returns Decimal instance
decimalParser.parse(true); // error, input is neither number nor string
```

I am not sure what would be the best way to do it in this project.
Looking at the code, I would either allow specifying custom zod constructors for various prisma field types in the options to `generator zod` or using some annotation in field documentation like the documentation extensions.

Furthermore, I think neither is possible before #54 is merged though, because we need a way to dynamically import from `decimal.js`.

**Comment by michalochman** [comment]
I've been playing with more types and it seems I have the same issue with `DateTime` type.

The type generated by `zod-prisma` is `z.date().nullable()`, however when considering the same scenario as above, i.e. data coming from some HTTP API, I would rather get a string representation of date, not a `Date` instance, e.g. "2021-12-30" or "2021-12-30T13:37:42".

Here is how one could do it using `preprocess` this time instead of transform (but either would work):

```ts
import { z } from "zod";

const zodPrismaDateParser = z.date().nullable()
zodPrismaDateParser.safeParse(new Date()); // ok
zodPrismaDateParser.safeParse(new Date("2021-12-30")); // ok
zodPrismaDateParser.safeParse("2021-12-30"); // error, input is not an instance of Date
zodPrismaDateParser.safeParse("2021-12-30T13:37:42"); // error, input is not an instance of Date

const dateParser = z.preprocess((v) => new Date(v), z.date()).nullable();

dateParser.safeParse(1640000000000); // ok
dateParser.safeParse(-1000000000000); // ok
dateParser.safeParse("2021-12-30"); // ok
dateParser.safeParse("2021-12-30T13:37:42"); // ok
dateParser.safeParse("2021-12-30T13:37:42-06:00"); // ok
dateParser.safeParse(new Date()); // ok
dateParser.safeParse(new Date(2021-12-30)); // ok
dateParser.safeParse("date"); // error, input cannot be parsed by Date
dateParser.safeParse({}); // error, input cannot be parsed by Date
```

Unfortunately it is not possible to express in schema currently.

**Comment by CarterGrimmeisen** [comment]
Hey @michalochman, take a loot at [the config-import functional test](https://github.com/CarterGrimmeisen/zod-prisma/tree/b69267b31b6a252406fb0c0eb1040ffd8bdeff9b/test/functional/config-import) and make sure it addresses your use case. I think it should provide a solution for both of these problems but let me know if you have any thoughts!

**Comment by michalochman** [comment]
Sweet @CarterGrimmeisen! I built it from feature branch, ran generator in my codebase and all is working as intended with both cases.

**Comment by CarterGrimmeisen** [comment]
0.5.0 has been published with this capability!
