### ISSUE TITLE
Allow to run prettier/custom formatter post-generate

### ISSUE THREAD

**Issue by zomars** [CarterGrimmeisen/zod-prisma#73]
What would be the optimal way to do this?

**Comment by franky47** [comment]
I'd say it's out of the scope of this package, but running [`prettier --write`](https://prettier.io/docs/en/cli.html#--write) after `prisma generate` on the generated files works for me, though I generally don't consider it critical if generated files aren't formatted like the rest of the code.

**Comment by CarterGrimmeisen** [comment]
As an avid user of prettier, I could definitely be convinced to include this feature. One thing that I'll note though is that the intention of this generator is that the generated code is not source controlled. Ideally this means the generated zod schemas shouldn't need to be included in your normal linting/formatting process.

**Comment by zomars** [comment]
I've ended up adding this script to my `package.json`:

```
"generate-schemas": "prisma generate && prettier --write ./prisma",
```

**Comment by CarterGrimmeisen** [comment]
Awesome! Glad you found something that works for you. Perhaps I'll add something to the readme that indicates this can be done for people who really want their specific formatting on the generated files.
