### ISSUE TITLE
Ability to use z.prepocess

### ISSUE THREAD

**Issue by fergusmeiklejohn** [CarterGrimmeisen/zod-prisma#75]
Hi Carter, I'm been playing around with trying to pass in `z.prepocess` in the Prisma comments because I need to preprocess an empty string to undefined so zod plays nicely with browser formData: The function is:
```ts
export function optionalField(zodValidation: z.ZodNullable<z.ZodString>) {
  return z.preprocess((val) => (val === "" ? undefined : val), zodValidation);
}
```
I can't pass a function in the comments so I tried the direct route:
```
/// @zod.preprocess((val) => (val === "" ? undefined : val), z.min(1).max(600))
```
but that creates:
```
z.string().nullable().preprocess((val) => (val === "" ? undefined : val), z.min(1).max(600)),
```
while we're looking for:
```
z.preprocess((val) => (val === "" ? undefined : val), z.string().min(1).max(600).nullable()),
```

What do you think, is this doable?

**Comment by franky47** [comment]
This should be possible with #69, which allows defining custom types in a separate user-defined file.

**Comment by CarterGrimmeisen** [comment]
Yep, as @franky47 said, this was one of the primary goals for #69. I'll go ahead and close this issue once a new release has been pushed with that included!

**Comment by CarterGrimmeisen** [comment]
0.5.0 has been published with this capability!
