### ISSUE TITLE
Is there a way to tell zod to use nullish instead of nullable?

### ISSUE THREAD

**Issue by zomars** [CarterGrimmeisen/zod-prisma#78]
I'm encountering many cases of:

```
Type 'number | null | undefined' is not assignable to type 'number | undefined'.
```

Using nullish instead for optional fields could solve this issue.

**Comment by CarterGrimmeisen** [comment]
Good catch! This makes perfect sense, I'll get that change made here in the next update!

**Comment by CarterGrimmeisen** [comment]
0.5.0 has been published with this change!

**Comment by CarterGrimmeisen** [comment]
Aside from breaking lots of things, I'm not sure this makes sense. I need to take a closer look at the Prisma generated types to see when undefined is necessary.

**Comment by CarterGrimmeisen** [comment]
@zomars can you provide a reproduction for the original error this issue relates to?

**Comment by zomars** [comment]
@CarterGrimmeisen would you kindly publish `0.5.2` to npm?

**Comment by CarterGrimmeisen** [comment]
Published.
