### ISSUE TITLE
Incorrect imports file path when stored in the output directory

### ISSUE THREAD

**Issue by franky47** [CarterGrimmeisen/zod-prisma#83]
First off, thanks a lot for v5.0.1, the imports feature is awesome!

I initially tried to store the imports file in the output directory, and the resolved path was missing a `./` prefix, example:

```prisma
generator zod {
  provider      = "zod-prisma"
  output        = "./schemas"
  imports       = "./schemas/_imports"
}
```

```ts
import * from '_imports'
// should be import * from './_imports'
```

Now, this is probably a stupid idea to store this file there, so I've moved it somewhere else, no rush for a fix.

**Comment by CarterGrimmeisen** [comment]
Oops! That's an easy fix. I'll have a fix for that soon!

**Comment by CarterGrimmeisen** [comment]
0.5.2 has been published with a fix for this.
