### ISSUE TITLE
zod.custom() bug

### ISSUE THREAD

**Issue by fergusmeiklejohn** [CarterGrimmeisen/zod-prisma#86]
Hey Carter, I like the new version of the library!

I just found a bug parsing `zod.custom()`:

```
url         String?          @db.VarChar(400) /// @zod.custom(z.string().min(1).refine((val) => isURL(val))) 
```

Is producing this: `z.string(.refine((val).nullish()`

So there is this parsing bug, but also reading the docs I understand that we need to specify it's a string but I'm not sure whether I should also specify it's nullish

**Comment by CarterGrimmeisen** [comment]
While this is definitely a bug that needs to be addressed, is there any reason you'd use this over the following? 

```prisma
url     String? /// @zod.min(1).url()
```

**Comment by fergusmeiklejohn** [comment]
I use the validator library over z.url() because zod requires `https://` which most users wouldn't type. If they copy/paste then it'll be in there but if they type the url it won't
