### ISSUE TITLE
Is there a way of using the shortest path available?

### ISSUE THREAD

**Issue by zomars** [CarterGrimmeisen/zod-prisma#92]
To explain further, I'm migrating to a monotipo and the schema now imports like this. Although importing from `@prisma/client` works just fine. Is there a way to achieve this?

<img width="507" alt="image" src="https://user-images.githubusercontent.com/3504472/150900271-13da6688-a0fc-4144-9e22-59890edd7761.png">

**Comment by franky47** [comment]
I had a fix for that in #51, and I noticed the same relative path bubbling up to node_modules behaviour in v5.0.1, I'll have a look at what's going on.

**Comment by CarterGrimmeisen** [comment]
Ah yeah. I see what happened. I'll have a fix for this out asap. Thanks for the report.

**Comment by zomars** [comment]
Also some team mates on windows are reporting that the schema generation is messing up with the paths:

> `../../node_modules/@prisma/client` became `....\node_modules@prismaclient`

**Comment by CarterGrimmeisen** [comment]
Okay, thanks for the additional info. I'll take a look into that too

**Comment by CarterGrimmeisen** [comment]
0.5.4 which contains the fix for (hopefully) both of these issues has been published!

**Comment by zomars** [comment]
Awesome! Testing it right now!
