### ISSUE TITLE
Custom Type

### ISSUE THREAD

**Issue by donferi** [CarterGrimmeisen/zod-prisma#95]
Is there a way to override the type of a property?

My use case: I'm using [remix](https://github.com/remix-run/remix) which has this concept of "loaders". Whatever data you return from your loaders you have it available in your ui. However, since the loaders run on a server the data gets serialized with `JSON.stringify` this basically converts `Date` types to `String`.

This causes my prisma and zod-prisma types to be "incorrect". Is there a way I can force the type of a property?

**Comment by CarterGrimmeisen** [comment]
[This section of the README](https://github.com/CarterGrimmeisen/zod-prisma#custom-zod-schema) is probably what you're looking for.

**Comment by CarterGrimmeisen** [comment]
In your import file you could have something like
```typescript
export const dateStringSchema = ... // some zod schema
```

and then change the type to use the custom zod schema with
```prisma
model SomeModel {
  ...
  field Date /// @zod.custom(imports.dateStringSchema)
}
```

**Comment by donferi** [comment]
I sincerely apologize, I missed it. Worked beautifully ❤️

**Comment by CarterGrimmeisen** [comment]
No need to apologize! Feel free to reach out if you have any other question! :D
